# Generated by Django 4.2 on 2023-05-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='check_order',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
