# Generated by Django 4.2 on 2023-05-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_cart_check_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='check_order',
            field=models.CharField(max_length=8),
        ),
    ]
