# Generated by Django 4.2 on 2023-05-04 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_cart_check_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.seller'),
            preserve_default=False,
        ),
    ]
